### PR TITLE
Fix broken links on Configu Cloud Platform page

### LINKED ISSUE #51: Broken links on Configu Cloud Platform page
I found one broken link and two wrong links connected in the [Configu Cloud Platform page](https://configu.com/docs/configu-cloud/) (the page in the image below ) .

Screenshot 2023-10-19 182355

If you see carefully in the above image you can see that I have circled three links in total, that's where the problem occurs .
Exact problems are as follows :-
- **History & Versioning Link**
I get redirected to this broken link when I click on this link .

Screenshot 2023-10-19 182212

Whereas this is the right page to which I should get redirected .

Screenshot 2023-10-19 182639

- **Permissions Link**
In this one I get redirected to the wrong page, i.e., the settings page .

Screenshot 2023-10-19 182316

Whereas the write page to be redirected to is the authorization page as it contains the content about roles and permissions .

Screenshot 2023-10-19 182702

- **Tokens Link**
In tokens, I get redirected to the settings page that is same as in the case of `permissions link`, whereas I should get redirected to the tokens page .

Screenshot 2023-10-19 182724

**I would love to generate a PR to resolve this issue, So, can you please assign it to me given this issue is valid .**

### PR DESCRIPTION
**Pull request by SanchitMahajan236**
Closes #51 
Updated the three broken links on the Configu Cloud Platform page.

### CODE REVIEW

**Comment by SanchitMahajan236** [comment]
@pelegpor Can you please review and merge this PR under hacktoberfest

**Review by RichardAkman — APPROVED** [review]
Great catch! Thanks a lot for your contribution! 🎖️

**Comment by SanchitMahajan236** [comment]
Hey, One of my friend told me recently that if you contributed in some particular repos, you can get swags and the list contained configu's name. So, I just wanted to confirm that am I eligible for the swag ??

**Comment by RichardAkman** [comment]
@SanchitMahajan236 details regarding [contributions during Hacktoberfest](https://github.com/configu/configu/issues/266) will be provided very soon!

**Comment by RichardAkman** [comment]
> Hey, One of my friend told me recently that if you contributed in some particular repos, you can get swags and the list contained configu's name. So, I just wanted to confirm that am I eligible for the swag ??

Hi, check out the [following link](https://github.com/configu/configu/issues/266#issuecomment-1826770636) for details regarding the Hacktoberfest rewards

**Pull request merged**
