### PR TITLE
Docs refactoring

### PR DESCRIPTION
**Pull request by bolotskydev**
**Describe the changes** 

This commit makes sure the latest docs content changes are legit in terms of UI

### CODE REVIEW

**Comment by bolotskydev** [comment]
Hey @pelegpor @gevaperry , please, verify the changes!

**Comment by rannn505** [comment]
@bolotskydev Thanks for those changes but Im currently working on the /CLI and /Concepts files and these changes will conflict with them so please remove your from the PR or split it to another PR that you will be able to later merge from main after I will merge my content.

**Comment by bolotskydev** [comment]
сс @yasell

**Comment by yasell** [comment]
Hi @rannn505! Removed /CLI and /Concepts file changes from the PR, please review

**Pull request merged**
