### PR TITLE
Update terminology.mdx

### PR DESCRIPTION
**Pull request by neelshah2409**
Added Definition of Configuration Source and Configuration Provider 

Associated Issue : #47

### CODE REVIEW

**Comment by neelshah2409** [comment]
Hey @pelegpor please review the PR

**Comment by RichardAkman** [comment]
Apologies for the delay! We've been taking a close look at the new terminologies you've proposed, and while they don't quite align with our vision, we truly appreciate your effort. Even though we're closing this PR, we've decided to welcome your contribution into our Hacktoberfest-approved list internally, so you can still claim those well-deserved rewards. Thank you for your hard work and understanding!

**Comment by neelshah2409** [comment]
> Apologies for the delay! We've been taking a close look at the new terminologies you've proposed, and while they don't quite align with our vision, we truly appreciate your effort. Even though we're closing this PR, we've decided to welcome your contribution into our Hacktoberfest-approved list internally, so you can still claim those well-deserved rewards. Thank you for your hard work and understanding!

Hey @RichardAkman no worries I would still be working on other issues though 
And how I can claim those rewards?

**Comment by RichardAkman** [comment]
@neelshah2409 we will publish the details within the next few days in all of our open-source repositories, stay tuned!

**Comment by RichardAkman** [comment]
@neelshah2409 check out the [following link](https://github.com/configu/configu/issues/266#issuecomment-1826770636) for details regarding the Hacktoberfest rewards

**Pull request closed without merging**
